version: '3'

services:
  all: # поднимает все сервисы монолитно
    image: all:latest
    build:
      context: .
      dockerfile: ./build/all/Dockerfile
      tags:
        - all:latest
    container_name: all
    ports:
      - "8080:80"

#  adminka:
#    image: adminka:latest
#    build:
#      context: .
#      dockerfile: ./build/adminka/Dockerfile
#      tags:
#       - adminka:latest
#    container_name: adminka
#    ports:
#      - "8080:8080"
#
#  auth:
#    image: auth:latest
#    build:
#      context: .
#      dockerfile: ./build/auth/Dockerfile
#      tags:
#        - auth:latest
#    container_name: auth
#    ports:
#      - "8081:8080"
#
#  broadcast:
#    image: broadcast:latest
#    build:
#      context: .
#      dockerfile: ./build/broadcast/Dockerfile
#      tags:
#        - broadcast:latest
#    container_name: broadcast
#    ports:
#      - "8082:8080"
#
#  news:
#    image: news:latest
#    build:
#      context: .
#      dockerfile: ./build/news/Dockerfile
#      tags:
#        - news:latest
#    container_name: news
#    ports:
#      - "8083:8080"
#
#  podcast:
#    image: podcast:latest
#    build:
#      context: .
#      dockerfile: ./build/podcast/Dockerfile
#      tags:
#        - podcast:latest
#    container_name: podcast
#    ports:
#      - "8084:8080"
